name: cookpedia
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  uuid: ^3.0.7
  firebase_storage: ^11.0.14
  fluttertoast: ^8.2.1
  google_fonts: ^4.0.3
  image_picker: ^0.8.6+2
  provider: ^6.0.5
  flutter_slidable: ^2.0.0
  http: ^0.13.5
  timeago: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/recipe.png'
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/recipe.png
    - assets/user.jpg
    - assets/image_placeholder.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
