// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhQcxnv4bQCAftVuIFKsOWH87msjdeJto',
    appId: '1:677584202909:web:13054d360a819668633874',
    messagingSenderId: '677584202909',
    projectId: 'cookpedia-a07a7',
    authDomain: 'cookpedia-a07a7.firebaseapp.com',
    storageBucket: 'cookpedia-a07a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjU4AuQmJd3PR0c2Z9GGE2oMXFLbUisZo',
    appId: '1:677584202909:android:bc94966a1b22b331633874',
    messagingSenderId: '677584202909',
    projectId: 'cookpedia-a07a7',
    storageBucket: 'cookpedia-a07a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeEHsVjJEp3HgAt-fwP2HyAwda5yYUBPc',
    appId: '1:677584202909:ios:c8bd648f01eaade6633874',
    messagingSenderId: '677584202909',
    projectId: 'cookpedia-a07a7',
    storageBucket: 'cookpedia-a07a7.appspot.com',
    iosClientId: '677584202909-viv5a7silqkh1gbov8f3lsbf3gs7gk1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookpedia',
  );
}
